# make sure proper venv is activated. Before running.
seed: 41
platform: torch 
path_to_trained_model: ./models/
# CIFAR-10 Dataset
image_size: 32
image_channels: 3
num_classes: 10 
# Model to use and it's config data
model_name: VGG16
epochs: 15 # 15 for VGG16, 10 for MobileNetv2 to prevent overfitting.
use_gpu: True
train_size: 0.8
batch_size: 64
learning_rate: 0.0001
topk: 3 # top k in accuracy
num_batches: 50 # for stable results.

# momentum: 0.9

